Repository jenkinsci/run-condition-plugin, pull requests merged in 2020-12, with the labels that each got.

#14 Nuget trigger + XTrigger support correction
  src/main/java/org/jenkins_ci/plugins/run_condition/core/CauseCondition.java
Labels: enhancement

#21 Update dependencies, use bom + new baseline
  pom.xml
Labels: chore

#23 Add release drafter
  .github/workflows/changelog.yml
  CHANGELOG-old.md
Labels: chore

#22 Tables to divs compatibility
  pom.xml
  src/main/resources/lib/runConditionPlugin/blockWrapper.jelly
  src/main/resources/org/jenkins_ci/plugins/run_condition/core/DayCondition/SelectDays/config.jelly
  src/main/resources/org/jenkins_ci/plugins/run_condition/logic/And/config.jelly
  src/main/resources/org/jenkins_ci/plugins/run_condition/logic/Or/config.jelly
Labels: enhancement

#24 Update bom
  pom.xml
Labels: dependencies
